services:
  mongo:
    image: mongo
    volumes: 
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  project-service:
    build: ./backend/project-service
    ports: 
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://localhost:27017/Project_DB
    depends_on:
      - mongo
  # task-service:
  #   build: 
  #     context: ./backend/task-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     MONGODB_URI: mongodb://mongo:27017/Task_DB
  #   depends_on:
  #     - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - project-service
      # - task-service
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - project-service
      # - task-service
volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge